# Generated by Django 5.2.4 on 2025-08-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("softdesk", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(
                choices=[
                    ("back-end", "Back-end"),
                    ("front-end", "Front-end"),
                    ("iOS", "iOS"),
                    ("Android", "Android"),
                ],
                max_length=20,
            ),
        ),
    ]
