# Generated by Django 5.2.4 on 2025-08-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("softdesk", "0004_comment_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="uuid",
        ),
        migrations.AddField(
            model_name="comment",
            name="custom_id",
            field=models.CharField(
                default=5, editable=False, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
